# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63lassification.proto\x12\x05proto\" \n\x0f\x43lassifyRequest\x12\r\n\x05query\x18\x01 \x01(\t\"6\n\x10\x43lassifyResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\npercentage\x18\x02 \x01(\x02\x32N\n\x0f\x43lassifyService\x12;\n\x08\x43lassify\x12\x16.proto.ClassifyRequest\x1a\x17.proto.ClassifyResponseB2Z0github.com/ary82/balance/internal/classificationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/ary82/balance/internal/classification'
  _globals['_CLASSIFYREQUEST']._serialized_start=31
  _globals['_CLASSIFYREQUEST']._serialized_end=63
  _globals['_CLASSIFYRESPONSE']._serialized_start=65
  _globals['_CLASSIFYRESPONSE']._serialized_end=119
  _globals['_CLASSIFYSERVICE']._serialized_start=121
  _globals['_CLASSIFYSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
